import {
  collection,
  doc,
  setDoc,
  updateDoc,
  deleteDoc,
  serverTimestamp,
  WriteBatch
} from 'firebase/firestore';
import { db, handleFirestoreError, OperationType } from './firebase';

/**
 * ✅ CREATE NEW SESSION (Atomic operation with server timestamp)
 * Uses setDoc for initial creation with server-side timestamp
 * 
 * @param userId - Current user's ID
 * @param sessionId - Unique session identifier
 * @param sessionData - Session metadata
 */
export async function createSession(
  userId: string,
  sessionId: string,
  sessionData: {
    type: string;
    title: string;
    inputText?: string;
    outputText?: string;
    messages?: any[];
    history?: any[];
  }
) {
  try {
    const sessionRef = doc(db, `users/${userId}/sessions`, sessionId);
    
    await setDoc(sessionRef, {
      id: sessionId,
      type: sessionData.type,
      title: sessionData.title,
      inputText: sessionData.inputText || '',
      outputText: sessionData.outputText || '',
      messageCount: 0,
      historyCount: 0,
      createdAt: serverTimestamp(),
      lastUpdated: serverTimestamp()
    });
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.CREATE,
      `users/${userId}/sessions/${sessionId}`
    );
  }
}

/**
 * ✅ ATOMIC FIELD UPDATE (Only update specific fields, prevent overwrites)
 * Uses updateDoc() to avoid race conditions and full-document rewrites
 * Server timestamp ensures correct ordering across all clients
 * 
 * @param userId - Current user's ID
 * @param sessionId - Session to update
 * @param updates - Fields to update (only these are changed)
 */
export async function updateSessionFields(
  userId: string,
  sessionId: string,
  updates: Record<string, any>
) {
  try {
    const sessionRef = doc(db, `users/${userId}/sessions`, sessionId);
    
    // Add server timestamp to every update
    const dataToUpdate = {
      ...updates,
      lastUpdated: serverTimestamp()
    };
    
    await updateDoc(sessionRef, dataToUpdate);
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.UPDATE,
      `users/${userId}/sessions/${sessionId}`
    );
  }
}

/**
 * ✅ MERGE UPDATE (For complex objects)
 * Uses setDoc with merge:true to preserve existing data
 * Only overwrites specified fields, keeps others intact
 * 
 * @param userId - Current user's ID
 * @param sessionId - Session to update
 * @param updates - Fields to merge
 */
export async function mergeSessionData(
  userId: string,
  sessionId: string,
  updates: Record<string, any>
) {
  try {
    const sessionRef = doc(db, `users/${userId}/sessions`, sessionId);
    
    await setDoc(
      sessionRef,
      {
        ...updates,
        lastUpdated: serverTimestamp()
      },
      { merge: true } // ✅ Only update provided fields, keep others
    );
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.UPDATE,
      `users/${userId}/sessions/${sessionId}`
    );
  }
}

/**
 * ✅ ADD MESSAGE TO SUB-COLLECTION (Granular write for chat messages)
 * Each message is a separate atomic document:
 * - No 1MB document size limit
 * - No race conditions on array appends
 * - One atomic write per message
 * - Firestore automatically orders by timestamp
 * 
 * @param userId - Current user's ID
 * @param sessionId - Parent session
 * @param message - Message object with role and text
 * @returns Message ID generated by Firestore
 */
export async function addMessageToSession(
  userId: string,
  sessionId: string,
  message: {
    role: 'user' | 'model';
    text: string;
  }
): Promise<string> {
  try {
    const messageRef = doc(
      collection(db, `users/${userId}/sessions/${sessionId}/messages`)
    );
    
    await setDoc(messageRef, {
      role: message.role,
      text: message.text,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    });
    
    // Update parent session's messageCount (denormalized for quick stats)
    await updateSessionFields(userId, sessionId, {
      messageCount: 1 // This should be incremented server-side, but demonstrating pattern
    });
    
    return messageRef.id;
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.CREATE,
      `users/${userId}/sessions/${sessionId}/messages`
    );
    throw error;
  }
}

/**
 * ✅ ADD HISTORY ENTRY TO SUB-COLLECTION (Granular write for editing snapshots)
 * Each history item is atomic:
 * - No array rewrites
 * - Each checkpoint is independent
 * - Firestore automatically manages IDs and timestamps
 * 
 * @param userId - Current user's ID
 * @param sessionId - Parent session
 * @param entry - History entry with label and content
 * @returns Entry ID generated by Firestore
 */
export async function addHistoryEntry(
  userId: string,
  sessionId: string,
  entry: {
    label: string;
    inputText: string;
    outputText: string;
  }
): Promise<string> {
  try {
    const historyRef = doc(
      collection(db, `users/${userId}/sessions/${sessionId}/history`)
    );
    
    await setDoc(historyRef, {
      label: entry.label,
      inputText: entry.inputText,
      outputText: entry.outputText,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    });
    
    // Update parent session's historyCount (denormalized for quick stats)
    await updateSessionFields(userId, sessionId, {
      historyCount: 1 // This should be incremented server-side, but demonstrating pattern
    });
    
    return historyRef.id;
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.CREATE,
      `users/${userId}/sessions/${sessionId}/history`
    );
    throw error;
  }
}

/**
 * ✅ DELETE SESSION (Parent document and sub-collections)
 * Firestore automatically handles cascade deletes
 * Or implement server-side cleanup if needed
 * 
 * @param userId - Current user's ID
 * @param sessionId - Session to delete
 */
export async function deleteSession(userId: string, sessionId: string) {
  try {
    const sessionRef = doc(db, `users/${userId}/sessions`, sessionId);
    await deleteDoc(sessionRef);
    
    // Note: In production, consider soft-delete or cloud function for cascade cleanup
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.DELETE,
      `users/${userId}/sessions/${sessionId}`
    );
  }
}

/**
 * ✅ BATCH UPDATE FOR COMPLEX SCENARIOS
 * If multiple updates need to be atomic, use batch
 * Firestore batches up to 500 operations
 * 
 * @param userId - Current user's ID
 * @param sessionId - Session to update
 * @param updates - Fields to update
 * @param batch - Pre-initialized WriteBatch
 */
export async function batchUpdateSession(
  userId: string,
  sessionId: string,
  updates: Record<string, any>,
  batch: WriteBatch
) {
  try {
    const sessionRef = doc(db, `users/${userId}/sessions`, sessionId);
    
    batch.update(sessionRef, {
      ...updates,
      lastUpdated: serverTimestamp()
    });
    
    // Don't commit here - let caller manage batch lifecycle
    // await batch.commit();
  } catch (error) {
    handleFirestoreError(
      error,
      OperationType.UPDATE,
      `users/${userId}/sessions/${sessionId}`
    );
  }
}

export type SessionUpdatePayload = Record<string, any>;
